### ISSUE TITLE
If a vector graphic fails to decode, it's very difficult to determine which one it is.

### ISSUE THREAD

**Issue by dnfield** [dnfield/vector_graphics#125]
Exceptions look like this:

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test (but after the test had completed):
Bad state: Unknown type tag 2

When the exception was thrown, this was the stack:
#0      VectorGraphicsCodec.decode (package:vector_graphics_codec/vector_graphics_codec.dart:177:11)
#1      decodeVectorGraphics (package:vector_graphics/src/listener.dart:54:36)
#2      _VectorGraphicWidgetState._loadPicture.<anonymous closure> (package:vector_graphics/vector_graphics.dart:223:14)
<asynchronous suspension>
(elided 2 frames from dart:async)
```

It'd be nice to include the `debugName` somewhere.

**Comment by dnfield** [comment]
Or probably just implement better `toString` on `AssetBytesLoader` and `NetworkBytesLoader` or the keys they make.
