### ISSUE TITLE
Tessellation fails on M1 Mac

### ISSUE THREAD

**Issue by peterscodee** [dnfield/vector_graphics#82]
Steps to reproduce:
- Run the following command on an ARM Mac

```
vector_graphics_compiler -i example.svg -o example.bin --tessellate 
```
`vector_graphics_compiler -i example.svg -o example.bin --no-tessellate` works as expected.

The following exception will be thrown:
<details>
  <summary>Logs</summary>

```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/Users/[...]/flutter/bin/cache/artifacts/engine/darwin-x64/libtessellator.dylib': dlopen(/Users/[...]/flutter/bin/cache/artifacts/engine/darwin-x64/libtessellator.dylib, 0x0001): tried: '/Users/[...]/flutter/bin/cache/artifacts/engine/darwin-x64/libtessellator.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libtessellator.dylib' (no such file), '/usr/lib/libtessellator.dylib' (no such file)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      _dylib (package:vector_graphics_compiler/src/svg/tesselator.dart:16:54)
#3      _dylib (package:vector_graphics_compiler/src/svg/tesselator.dart)
#4      _createPathFn (package:vector_graphics_compiler/src/svg/tesselator.dart:291:5)
#5      _createPathFn (package:vector_graphics_compiler/src/svg/tesselator.dart)
#6      new VerticesBuilder (package:vector_graphics_compiler/src/svg/tesselator.dart:210:34)
#7      Tesselator.visitResolvedPath (package:vector_graphics_compiler/src/svg/tesselator.dart:108:39)
#8      ResolvedPathNode.accept (package:vector_graphics_compiler/src/svg/resolver.dart:251:20)
#9      Tesselator.visitViewportNode (package:vector_graphics_compiler/src/svg/tesselator.dart:188:57)
#10     ViewportNode.accept (package:vector_graphics_compiler/src/svg/node.dart:105:20)
#11     SvgParser.parse (package:vector_graphics_compiler/src/svg/parser.dart:643:25)
<asynchronous suspension>
#12     encodeSvg (package:vector_graphics_compiler/vector_graphics_compiler.dart:92:43)
<asynchronous suspension>
#13     main ([...]/vector_graphics/packages/vector_graphics_compiler/bin/vector_graphics_compiler.dart:58:27)
<asynchronous suspension>
```

</details>

<details>
  <summary>Flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.925, on macOS 12.2.1 21D62
    darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
[✓] IntelliJ IDEA Ultimate Edition (version EAP IC-221.5080.56)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
I didn't special case m1 to look up the right asset, we'd need to detect if we're running in rosetta or not and choose the binary based on that

**Comment by dnfield** [comment]
@dcharkes fyi

**Comment by dcharkes** [comment]
Does `Platform.version` report x64 when running rosetta?

**Comment by jonahwilliams** [comment]
No I think it probably works, but I just always try to run the x64 version.

**Comment by jonahwilliams** [comment]
https://github.com/dnfield/vector_graphics/blob/main/packages/vector_graphics_compiler/lib/src/initialize_tessellator.dart#L21

I'd need to check Platform.version here

**Comment by peterscodee** [comment]
Also, is it possible to use tessellation on the web? As you are calling native code, maybe a WebAssembly version could potentially work as well. My use case would be an online converter the community can use to convert SVG to binary.

**Comment by jonahwilliams** [comment]
We have no immediate plans to support running the compiler itself as a web target if tesselation is enabled.

**Comment by dnfield** [comment]
That said the engine does know how to build wasm now...

**Comment by jonahwilliams** [comment]
Turns out we don't have m1 prebuilts yet for our host tools. So running binaries workes because rosetta, but trying to open a dynamic library will fail. We'll have to circle back on this once everything is built for arm too

**Comment by jonahwilliams** [comment]
Un-assigning for now since we're blocked on this

**Comment by jonahwilliams** [comment]
This was fixed https://github.com/flutter/flutter/issues/110227
